### ISSUE TITLE
Error running candyman.deploy()

### ISSUE THREAD

**Issue by wmmihaa** [codefoster/candyman#1]
I used the configuration as you explained it on your pluralsight course (great course btw). Perhaps these settings has changed, but this is how I set it up:

``` javascript
var gulp = require('gulp');
var Candyman = require('candyman');

var candyman = new Candyman({
    targetDevices: [{
        devicename: 'rpi22', hostname: 'rpi22'
        }],
    projectName: 'microServiceBus',
    user: 'root',
    password: 'pi',
    startFile:'microServiceBusHost.js'
});

gulp.task('default', function () {
    console.log('Running default gulp');
});

gulp.task('deploy', function () {
    console.log('Running deploy gulp');
    return candyman.deploy();
});
```
## This is the exception i get:

Starting deploy task
'scp' is not recognized as an internal or external command,
operable program or batch file.

Error in deploy task on rpi22: Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "scp app.js package.json root@rpi22:/home/root/microServiceBus"
'scp' is not recognized as an internal or external command, operable program or batch file.

**Comment by codefoster** [comment]
In order for candyman to work, you have to have scp working at your command line in Windows. The candyman module simply uses the default command shell to execute local commands. You know it's going to work if you can type `scp` at the command line and you get something besides an error. The easiest way to get scp is to be sure you have git installed and then add a path to the git bin folder into the Windows path variable. Let me know if that doesn't clear this up.
